version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: project_planner
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - project_planner-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - project_planner-redis:/var/lib/redis/data

  project_planner:
    tty: true
    stdin_open: true
    build:
      context: .
    volumes:
      - ./project_planner:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - project_planner
    ports:
      - '8020:8020'

volumes:
  project_planner-postgres:
  project_planner-redis: